from __future__ import annotations


DEFAULT_MODEL = "qwen3:9b"
DEFAULT_BASE_URL = "http://localhost:11434"

DEFAULT_CHUNK_SIZE = 220
DEFAULT_CHUNK_OVERLAP = 50
DEFAULT_TOP_K = 4
DEFAULT_MEMORY_TURNS = 4

DEFAULT_TEMPERATURE = 0.2
DEFAULT_TOP_P = 0.9
DEFAULT_NUM_PREDICT = 220
